<?php
/*
 * Copyright (c) 2026 Payfast (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

?>
<div class="rk button">
    <form action="<?=
    /** @noinspection PhpUndefinedVariableInspection */
    $block->getGateUrl(); ?>" method="POST">
        <?php
        foreach ($block->getPostData() as $key => $value): ?>
            <input type="hidden" name="<?= $escaper->escapeHtml($key); ?>"
                   value="<?= $escaper->escapeHtml($value); ?>"></input>
            <?php
        endforeach; ?>
        <button type="submit">Pay</button>
    </form>
</div>
