<?php
/*
 * Copyright (c) 2026 Payfast (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */

?>
<h2><?=
    /** @noinspection PhpUndefinedVariableInspection */
    $escaper->escapeHtml($block->getMessage()); ?></h2>

<form name="<?= $escaper->escapeHtml($block->getName()); ?>"
      id="<?= $escaper->escapeHtml($block->getId()); ?>"
      action="<?= $escaper->escapeHtml($block->getFormAction()); ?>"
      method="post">

    <?php
    foreach ($block->getFormData() as $item => $value): ?>
        <input type="hidden" name="<?=
        $escaper->escapeHtml($item); ?>" value="<?=
        $escaper->escapeHtml($value); ?>" size="200">
        <?php
    endforeach; ?>
</form>
<?= /* @noEscape */
$block->getSubmitForm(); ?>
